module.exports = {
  product: '40344',
  page: 0,
  count: 5,
  results: [
    {
      review_id: 1275717,
      rating: 3,
      summary: 'sdafasdffa',
      recommend: false,
      response: null,
      body: 'asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdffasdfasdfasdfasdf',
      date: '2022-07-19T00:00:00.000Z',
      reviewer_name: 'asdfasdf',
      helpfulness: 0,
      photos: [],
    },
    {
      review_id: 1275716,
      rating: 4,
      summary: 'sdfasdfda',
      recommend: false,
      response: null,
      body: 'sdfasdfdasdfasdfdasdfasdfdasdfasdfdasdfasdfdasdfasdfdasdfasdfdasdfasdfda',
      date: '2022-07-19T00:00:00.000Z',
      reviewer_name: 'sdfasdf',
      helpfulness: 0,
      photos: [],
    },
    {
      review_id: 1275715,
      rating: 2,
      summary: 'adfasdfasdf',
      recommend: false,
      response: null,
      body: 'asdfasdfadsfasdfasdfadsfasdfasdfadsfasdfasdfadsfasdfasdfadsf',
      date: '2022-07-19T00:00:00.000Z',
      reviewer_name: 'sadfasdf',
      helpfulness: 0,
      photos: [],
    },
    {
      review_id: 1275714,
      rating: 2,
      summary: 'asdfasdf',
      recommend: true,
      response: null,
      body: 'asdfasdfasdfasasdfasdfasdfasasdfasdfasdfasasdfasdfasdfas',
      date: '2022-07-19T00:00:00.000Z',
      reviewer_name: 'sfasdf',
      helpfulness: 0,
      photos: [],
    },
    {
      review_id: 1275711,
      rating: 4,
      summary: 'asdfasdf',
      recommend: true,
      response: null,
      body: 'asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf',
      date: '2022-07-19T00:00:00.000Z',
      reviewer_name: 'sadfasdf',
      helpfulness: 0,
      photos: [],
    },
  ],
};
